### ISSUE TITLE
header level above 6

### ISSUE THREAD

**Issue by MrApe** [sergiocorreia/panflute#105]
I'm using [pandoc-latex-color](https://github.com/chdemko/pandoc-latex-color) filter, which in turn uses `panflute`. My document is rather large having more than the fixed 6 header levels and thus `panflute` raises an error:

```
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-latex-color", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pandoc_latex_color.py", line 361, in main
    return run_filter(colorize, prepare=prepare, finalize=finalize, doc=doc)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 260, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 233, in run_filters
    doc = load(input_stream=input_stream)
  File "/usr/local/lib/python3.7/site-packages/panflute/io.py", line 56, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 361, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/lib/python3.7/site-packages/panflute/elements.py", line 1402, in from_json
    return Header(*c[2], level=c[0], **_decode_ica(c[1]))
  File "/usr/local/lib/python3.7/site-packages/panflute/elements.py", line 366, in __init__
    raise TypeError('Header level not between 1 and 6')
TypeError: Header level not between 1 and 6
Error running filter pandoc-latex-color:
Filter returned error status 1
```

Why is this restriction necessary and how do I handle this problem?

Thanks and Regards, 

Jonas

**Comment by sergiocorreia** [comment]
The restriction on 6 levels is arbitrary; I was not aware there was a use
case for this, nor that Pandoc allowed it .

You can do a PR if desired lifting the restriction, or I can try fixing it
from here hopefully within a couple of days.

**Comment by MrApe** [comment]
I worked around it for now by reducing my header levels but a fix would be nice. At least 7 levels are required when building a full LaTeX document (part, chapter, section, subsection, subsubsection, paragraph, subparagraph). [Source](https://en.wikibooks.org/wiki/LaTeX/Document_Structure#Sectioning_commands)
Am 10. Juli 2019, 16:39 +0200 schrieb Sergio Correia <notifications@github.com>:

**Comment by ptmkenny** [comment]
Hi, I just wanted to note I had the same problem.  I am using Panflute to convert an OPML (outline) document into Markdown.  My OPML outline goes about 10 levels deep, and I want to use a panflute filter to make h1 to h6 for the first six levels, and then plain text after that, but currently I have to compress everything into six levels or I get the error described here.

**Comment by sergiocorreia** [comment]
I did a tiny edit that should have fix this problem (allowed up to ten levels deep). Let me know if it works so I can close the issue.

**Comment by ptmkenny** [comment]
@sergiocorreia How can I test the change?  I tried to update panflute with `pip install --upgrade panflute` but it says I am still on the latest version (1.11.2).

**Comment by ptmkenny** [comment]
@sergiocorreia Ok, I found the dev instructions and set up a dev environment locally and installed the latest version-- and it works!  I have 8 header levels in my OPML document and the conversion to markdown goes smoothly!  Thanks for fixing this.

**Comment by eudoxos** [comment]
I am just trying to process a (rather broken) Word document where the authors used styles called Header31 and similar; I would say panflute should grok whatever pandoc parses, which in my cases is header level 31 (I edited panflute locally now); and of course the filter I am writing is to fix the TOC structure.
