### ISSUE TITLE
Can't run Jupyter kernel from inside panflute filter.

### ISSUE THREAD

**Issue by jhidding** [sergiocorreia/panflute#120]
Not sure if this is an issue with `jupyter_client` or `panflute`. Taking this minimal example (call it test-jupyter.py):

```python
#!/usr/bin/env python3.7

import panflute
import jupyter_client
import sys

def action(elem, doc):
    pass

def finalize(doc):
    with jupyter_client.run_kernel(kernel_name="python3") as kc:
        print(kc.is_alive(), file=sys.stderr)

def main(doc=None):
    return panflute.run_filter(action, finalize=finalize)

if __name__ == "__main__":
    main()
```

And running it with

    chmod +x jupyter_test.py
    pandoc -t plain --filter jupyter_test.py

(press Ctrl-D to end input)
Gives the following error:

```
Traceback (most recent call last):
  File "/home/johannes/.local/lib/python3.7/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'kernel_dirs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test-jupyter.py", line 18, in <module>
    main()
  File "./test-jupyter.py", line 15, in main
    return panflute.run_filter(action, finalize=finalize)
  File "/home/johannes/.local/lib/python3.7/site-packages/panflute/io.py", line 260, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/home/johannes/.local/lib/python3.7/site-packages/panflute/io.py", line 244, in run_filters
    finalize(doc)
  File "./test-jupyter.py", line 11, in finalize
    with jupyter_client.run_kernel(kernel_name="python3") as kc:
  File "/usr/lib64/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/manager.py", line 490, in run_kernel
    km, kc = start_new_kernel(**kwargs)
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/manager.py", line 468, in start_new_kernel
    km.start_kernel(**kwargs)
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 234, in get_kernel_spec
    resource_dir = self._find_spec_directory(kernel_name.lower())
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 205, in _find_spec_directory
    for kernel_dir in self.kernel_dirs:
  File "/home/johannes/.local/lib/python3.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/johannes/.local/lib/python3.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/johannes/.local/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 151, in _kernel_dirs_default
    from IPython.paths import get_ipython_dir
  File "/home/johannes/.local/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/johannes/.local/lib/python3.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/johannes/.local/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 81, in <module>
    if not _stream or not hasattr(_stream, 'isatty') or not _stream.isatty():
ValueError: I/O operation on closed file
Error running filter test-jupyter.py:
Filter returned error status 1
```

Just running `finalize(None)` and calling that outside the `panflute` framework works fine. Somehow the magic inside `traitlets` is affected by `panflute`, but I can't fathom how.

Any help is much appreciated.
Regards, Johan

Related issue: https://github.com/jupyter/jupyter_client/issues/497#issue-529212945

**Comment by jhidding** [comment]
It turns out, jupyter_client doesn't work with `sys.stdout` closed. I consider this an issue with Jupyter.
