### ISSUE TITLE
Number of table columns is 0 when no header is given

### ISSUE THREAD

**Issue by pwwang** [sergiocorreia/panflute#128]
It worked in v1.11.2, but broke in v1.12.3

```python
from panflute import *
# ...
def fenced_action(options, data, element, doc):
  table = Table(
       TableRow(TableCell(Plain(Str(''))), 
           TableCell(Plain(Str('Quality'))), 
           TableCell(Plain(Str('Age'))), 
           TableCell(Plain(Str('Sex'))),
           TableCell(Plain(Str('Memo')))),
       header = None, # no header is given
       caption = [Str('Whatever caption')], 
       width = [0.16, 0.16, 0.16, 0.16, 0.16], 
       alignment = ['AlignDefault', 'AlignDefault', 
          'AlignDefault', 'AlignDefault', 'AlignDefault'])
  return Div(table)

def main(doc=None):
  return run_filter(yaml_filter, tag='table', function=fenced_action, doc=doc)

if __name__ == '__main__':
  main()
```

When running pandoc with it:
```shell
Traceback (most recent call last):
  File "/[path]/filetable.py", line 140, in <module>
    main()
  File "/[path]/filetable.py", line 137, in main
    return run_filter(yaml_filter, tag='table', function=fenced_action, doc=doc)
  File "/[path]/lib/python3.7/site-packages/panflute/io.py", line 258, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/[path]/lib/python3.7/site-packages/panflute/io.py", line 239, in run_filters
    doc = doc.walk(action, doc)
  File "/[path]/lib/python3.7/site-packages/panflute/base.py", line 265, in walk
    ans = list(chain.from_iterable(ans))
  File "/[path]/lib/python3.7/site-packages/panflute/base.py", line 263, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/[path]/lib/python3.7/site-packages/panflute/base.py", line 260, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/[path]/lib/python3.7/site-packages/panflute/base.py", line 276, in walk
    altered = action(self, doc)
  File "/[path]/lib/python3.7/site-packages/panflute/tools.py", line 149, in yaml_filter
    element=element, doc=doc)
  File "/[path]/filetable.py", line 128, in fenced_action
    header=header or [], caption=caption, width=width, alignment = align)
  File "/[path]/lib/python3.7/site-packages/panflute/elements.py", line 1072, in __init__
    raise IndexError('alignment has an incorrect number of cols')
IndexError: alignment has an incorrect number of cols
Error running filter /[path]/filetable.py:
Filter returned error status 1
```

```shell
> pandoc --version                      
pandoc 2.7.3
Compiled with pandoc-types 1.17.5.4, texmath 0.11.2.2, skylighting 0.8.1
Default user data directory: /[path]/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

> grep __version__ /[path]/lib/python3.7/site-packages/panflute/version.py 
__version__ = '1.12.3'
```

It worked perfectly in `1.11.2`

I took a look at `/[path]/lib/python3.7/site-packages/panflute/elements.py` and found that `self.cols == 0` because of value `None` of `header`.

It makes more sense of that in `1.11.2` of determining the # columns:
```python
self.cols = len(self.content[0].content) # Line 1060
```

If this is an intended change, then an error should be raised if no header is given.

**Comment by sergiocorreia** [comment]
Do you have a markdown file on hand that I can use to test this?

**Comment by pwwang** [comment]
A simple markdown file with following will do:
````markdown
```table
```
````

In order to make it simple, I didn't really read the data from the fence.

**Comment by sergiocorreia** [comment]
Latest commit should have fixed it (check the commit msg). Let me know if you find any other problems or issues.
