### ISSUE TITLE
Exception: unknown tag: LineBlock

### ISSUE THREAD

**Issue by ickc** [sergiocorreia/panflute#32]
Somewhat MWE:

```bash
printf "%s\n" '| abc' '| def' | pandoc -f markdown -t native -F pantable2csv
Traceback (most recent call last):
  File "/usr/local/bin/pantable2csv", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/pantable/pantable2csv.py", line 127, in main
    panflute.run_filter(table2csv)
  File "/usr/local/lib/python3.5/site-packages/panflute/io.py", line 257, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/panflute/io.py", line 230, in run_filters
    doc = load(input_stream=input_stream)
  File "/usr/local/lib/python3.5/site-packages/panflute/io.py", line 53, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/usr/local/lib/python3.5/site-packages/panflute/elements.py", line 1459, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: LineBlock
pandoc: Error running filter pantable2csv
Filter returned error status 1
```

looking at the source in `panflute/elements.py`, LineBlock is not defined.

**Comment by ickc** [comment]
Reference: [Text.Pandoc.Definition](https://hackage.haskell.org/package/pandoc-types-1.17.0.4/docs/Text-Pandoc-Definition.html#t:Inline)

**Comment by ickc** [comment]
I checked `elements.py` against [Text.Pandoc.Definition](https://hackage.haskell.org/package/pandoc-types-1.17.0.4/docs/Text-Pandoc-Definition.html#t:Inline). Among MetaValue, Block, and Inline, only LineBlock is missing.

I tried to create a simple fix, but LineBlock emit a list, so probably a class similar to `DefinitionItem(Element)` is needed, say, `LineBlockItem`?

**Comment by sergiocorreia** [comment]
Makes sense. It seems we need a `LineBlock` and a `LineBlockItem` (that inherits from `Element` as it's neither an Inline or a Block)

I can probably copy the code from `BulletList` and tweak it a bit. Expect a patch around tomorrow night.
