### ISSUE TITLE
UNIX: error as panflute.shell() replaces slash to backslash

### ISSUE THREAD

**Issue by K4zuki** [sergiocorreia/panflute#70]
## `panflute.shell()` internally replaces forward slash`/` of given argument to backslash`\` but this makes error on unix shell. 

```python
import panflute as pf

pf.shell("ls") # works
pf.shell("/bin/ls") # fails
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/panflute/tools.py", line 288, in shell
    proc = Popen(args, stdin=PIPE, stdout=PIPE, stderr=PIPE)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '\\bin\\ls'
```
---
Is this intended? Other way makes sense for me
because windows shell understands forward slash.

looks-like cause of error is in `tools.py`, line 285:
```python
...

    args = [arg.replace('/', '\\') for arg in args]

...
```
---
confirmed on Ubuntu 16.04 and MacOS

**Comment by sergiocorreia** [comment]
I vaguely recall adding that line for Windows, so I could make it depend on the is.

Feel free to send a PR request or else I should also be able to push a commit tonight.

**Comment by K4zuki** [comment]
Thanks! will wait for your fix
