### ISSUE TITLE
Tables with pipe rendering

### ISSUE THREAD

**Issue by chdemko** [sergiocorreia/panflute#76]
See https://github.com/chdemko/pandoc-numbering/issues/8

**Comment by aubertc** [comment]
As far as I can tell, this issue vanished.

```
|Solution +.#
~ 

    :---: | :---: 
    Pandoc | Is happy
```

can normally be compiled with

```
pandoc MWE.md --filter pandoc-numbering -o MWE.html
```

**Comment by aubertc** [comment]
As far as I can tell, this issue came back, but a bit differently.

If the table as a header, so if we have

```.md
Solution +.#
~  
    test | Ah !
    :---: | :---: 
    Pandoc | Is happy
```

and we compile it with

```
pandoc MWE.md --filter pandoc-numbering -o MWE.html
```

then we get

```
pandoc in.md --filter pandoc-numbering  -o test_pandoc-numbering.html 
Traceback (most recent call last):
  File "/usr/local/bin/pandoc-numbering", line 8, in <module>
    sys.exit(main())
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 1412, in main
    [numbering, referencing], prepare=prepare, doc=doc, finalize=finalize
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/io.py", line 205, in run_filters
    doc = doc.walk(action, doc)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 264, in walk
    ans = list(chain.from_iterable(ans))
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 262, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 259, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 264, in walk
    ans = list(chain.from_iterable(ans))
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 262, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 259, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 275, in walk
    altered = action(self, doc)
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 700, in numbering
    numbered = Numbered(elem, doc)
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 201, in __init__
    self._replace_marker()
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 235, in _replace_marker
    self._compute_data()
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 389, in _compute_data
    replace_description(self._elem, self._description)
  File "/home/caubert/.local/lib/python3.7/site-packages/pandoc_numbering.py", line 442, in replace_description
    where.walk(partial(replacing, search="%D", replace=copy.deepcopy(description)))
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 264, in walk
    ans = list(chain.from_iterable(ans))
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 262, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 259, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 264, in walk
    ans = list(chain.from_iterable(ans))
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 262, in <genexpr>
    ans = ((item,) if type(item) != list else item for item in ans)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 259, in <genexpr>
    ans = (item.walk(action, doc) for item in obj)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/base.py", line 272, in walk
    setattr(self, child, ans)
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/table_elements.py", line 113, in head
    self._head = check_type(value, TableHead) if value else TableHead()
  File "/home/caubert/.local/lib/python3.7/site-packages/panflute/utils.py", line 71, in check_type
    raise TypeError(msg)
TypeError: 

Element "Numbered" received "list" but expected <class 'panflute.table_elements.TableHead'>

Error running filter pandoc-numbering:
Filter returned error status 1
```

As far as I know, I'm running the latest version of pandoc (pandoc 2.11.1.1, Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.3,citeproc 0.1.1.1, ipynb 0.1.0.1), the latest version of panflute and the latest version of include-code.

**Comment by aubertc** [comment]
@sergiocorreia Should we re-open the issue, or do you want me to create a new one?

**Comment by sergiocorreia** [comment]
The latest versions of Pandoc and pandoc-tables revamped the Table() API, which we recently added to Panflute, so I guess the problems lies there.

I'm not familiar with the internals of `pandoc-numbering`, but it seems that it's trying to feed the .head of a table into a numbered list, which will fail (before, the head was just a list, now it's a proper object).

**Comment by aubertc** [comment]
Brief follow-up: the issue was actually that pandoc-numbering was using an outdated version of panflute. Bumping the version fixes that issue!

**Comment by chdemko** [comment]
I'm going to update pandoc-numbering when I will have some extra time
